# Generated by Django 5.2.3 on 2025-07-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
    ]
