# Generated by Django 5.2.3 on 2025-07-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Blog',
        ),
    ]
