# Generated by Django 5.2.3 on 2025-07-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spblog', '0002_rename_project_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, upload_to='spblog_images/'),
        ),
    ]
