# Generated by Django 5.0.14 on 2025-11-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text='List of ingredients, one per line or as free text.'),
        ),
    ]
